.PHONY: all clean

all:
	@echo "Building common utilities..."
	@# This is a header-only library for now, but if we had .c files:
	@# gcc -c utils.c -o utils.o

clean:
	@echo "Cleaning common utilities..."
	@# rm -f *.o
